### PR TITLE
fix: add comments back for the test

### PR DESCRIPTION
**Pull request by lasjorg**
The comments that were removed are needed for the tests.

https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-with-helmetjs/hash-and-compare-passwords-synchronously.md
https://github.com/freeCodeCamp/freeCodeCamp/blob/master/curriculum/challenges/english/09-information-security/information-security-with-helmetjs/hash-and-compare-passwords-asynchronously.md

### CODE REVIEW

**Comment by lasjorg** [comment]
@Sky020 @moT01 pinging for visibility, we need to get this fixed.

**Comment by ShaunSHamilton** [comment]
Should we not rather change the tests to not look for the comments?

**Comment by naomi-lgbt** [comment]
> Should we not rather change the tests to not look for the comments?

I would agree with this.

**Comment by lasjorg** [comment]
I don't really have a strong opinion either way, as long as it gets fixed.

**Comment by naomi-lgbt** [comment]
I'd be okay with merging this now to fix the error while we work on refactoring the tests.

@Sky020 what do you think?

**Review by ShaunSHamilton — APPROVED** [review]
LGTM 👍 Thanks, @lasjorg 

@nhcarrigan Yes, I agree. It is a couple more PRs, but might abate a couple campers' frustrations. Merge, if you are happy.

**Comment by lasjorg** [comment]
Adding the comments back, fixing the test, and then removing the comments again would likely cause the least amount of issues for people.

**Review by naomi-lgbt — APPROVED** [review]
LGTM~! 🥳 

Thank you for your pull request! We look forward to additional contributions!

**Pull request merged**
